import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import ProductCategoryCard from "@/components/productCategoryCard";
import WomenCategory from "@/assets/banner-01.jpg.webp";
import MenCategory from "@/assets/banner-02.jpg.webp";
import AccessoriesCategory from "@/assets/banner-03.jpg.webp";
import { useState } from "react";
import ProductCard from "@/components/productCard";
import Footer from "@/components/footer";
import HomeSlider from "@/components/homeSlider";
import AllProducts from "@/components/allProducts";

const inter = Inter({ subsets: ["latin"] });

const category = [
  {
    id: 1,
    type: "Women",
    img: WomenCategory,
  },
  {
    id: 2,
    type: "Men",
    img: MenCategory,
  },
  {
    id: 3,
    type: "Accessories",
    img: AccessoriesCategory,
  },
];

export default function Home({ setOpenSideCart }) {
  return (
    <>
      <Head>
        <title>Shoppy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeSlider />
      <main className="p-4">
        <section className="flex flex-col md:flex-row">
          {category.map((item) => {
            return <ProductCategoryCard data={item} key={item.id} />;
          })}
        </section>

        <section className="">
          <p className="mx-8 text-3xl font-bold">PRODUCT OVERVIEW</p>
          <AllProducts />
        </section>
      </main>
    </>
  );
}
